name: docs 
on:
  push:
    branches:
      - 'main'
      - '*mkdocs*'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install mkdocs dependencies
      - run: |
          pip install .
          pip install \
          'mkdocs>=1.4,<2' \
          'mkdocs-gen-files>=0.4,<1' \
          'mkdocs-literate-nav>=0.6,<1' \
          'mkdocs-material>=9.0,<10' \
          'mkdocs-section-index>=0.3,<1' \
          'mkdocstrings[python]>=0.8,<1'
          
      # Build and deploy
      - run: mkdocs gh-deploy --force
