name: Build & Test - NLP
on:
  push:
    branches:
      - 'main'
      - 'release/v*'
  pull_request:
    branches:
      - 'main'
      - 'release/v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Lint with flake8
        run: |
          # Create a new temporary project
          cd templates/template_nlp
          python generate_nlp_project.py -n tmp_project_flake8 -p tmp_project_flake8
          cd tmp_project_flake8
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --ignore=E501 --statistics
      - name: Test generate NLP
        run: |
          cd templates/template_nlp
          python nlp_tests/tests_setup.py
